version: '3.8'

services:
  waha:
    image: devlikeapro/waha
    container_name: wpp_bot_waha
    restart: always
    ports:
      - "127.0.0.1:3000:3000/tcp"
    
    volumes:
      - "./.sessions:/app/.sessions"
      - "./.media:/app/.media"

    env_file:
      - .env

  api:
    build: .
    container_name: wpp_bot_api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./chroma_data:/app/chroma_data
