version: '3.8'

services:
  waha:
    image: devlikeapro/waha
    container_name: wpp_bot_waha
    restart: always
    ports:
      - "3000:3000"

  api:
    build: .
    container_name: wpp_bot_api
    ports:
      - "5000:5000"
    volumes:
        - .:/app
        - ./chroma_data:/app/chroma_data
